// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCwTDZ9edUEBwBdUD_qadGUW144muohTjQ',
    appId: '1:1002864705973:web:99e933c5ffbd13057399fc',
    messagingSenderId: '1002864705973',
    projectId: 'chaty-a047a',
    authDomain: 'chaty-a047a.firebaseapp.com',
    storageBucket: 'chaty-a047a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCkNfitW9E6kxdo4flim81uXgOwlL20mkw',
    appId: '1:1002864705973:android:8dea6054ffed448d7399fc',
    messagingSenderId: '1002864705973',
    projectId: 'chaty-a047a',
    storageBucket: 'chaty-a047a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0MUAmxYvDEdM2YNG-1ve7gO0WpU_tARQ',
    appId: '1:1002864705973:ios:0ad78738db129bfd7399fc',
    messagingSenderId: '1002864705973',
    projectId: 'chaty-a047a',
    storageBucket: 'chaty-a047a.appspot.com',
    iosBundleId: 'com.lyrilab.chaty',
  );
}
